/*
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Parquet.Thrift
{
   /// <summary>
   /// Enum to annotate whether lists of min/max elements inside ColumnIndex
   /// are ordered and if so, in which direction.
   /// </summary>
   enum BoundaryOrder
   {
      UNORDERED = 0,
      ASCENDING = 1,
      DESCENDING = 2,
   }
}
