/*
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Parquet.Thrift
{
   /// <summary>
   /// Supported compression algorithms.
   /// 
   /// Codecs added in format version X.Y can be read by readers based on X.Y and later.
   /// Codec support may vary between readers based on the format version and
   /// libraries available at runtime.
   /// 
   /// See Compression.md for a detailed specification of these algorithms.
   /// </summary>
   enum CompressionCodec
   {
      UNCOMPRESSED = 0,
      SNAPPY = 1,
      GZIP = 2,
      LZO = 3,
      BROTLI = 4,
      LZ4 = 5,
      ZSTD = 6,
      LZ4_RAW = 7,
   }
}
