/*
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Parquet.Thrift
{
   /// <summary>
   /// Supported compression algorithms.
   /// 
   /// Codecs added in format version X.Y can be read by readers based on X.Y and later.
   /// Codec support may vary between readers based on the format version and
   /// libraries available at runtime.
   /// 
   /// See Compression.md for a detailed specification of these algorithms.
   /// </summary>
   public enum CompressionCodec
   {
      /// <summary>
      /// No compresison (default)
      /// </summary>
      UNCOMPRESSED = 0,

      /// <summary>
      /// 
      /// </summary>
      SNAPPY = 1,

      /// <summary>
      /// 
      /// </summary>
      GZIP = 2,

      /// <summary>
      /// 
      /// </summary>
      LZO = 3,

      /// <summary>
      /// 
      /// </summary>
      BROTLI = 4,

      /// <summary>
      /// 
      /// </summary>
      LZ4 = 5,

      /// <summary>
      /// 
      /// </summary>
      ZSTD = 6,

      /// <summary>
      /// 
      /// </summary>
      LZ4_RAW = 7,
   }
}
