/*
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Parquet.Thrift
{
   /// <summary>
   /// Representation of Schemas
   /// </summary>
   public enum FieldRepetitionType
   {
      /// <summary>
      /// This field is required (can not be null) and each record has exactly 1 value.
      /// </summary>
      REQUIRED = 0,
      /// <summary>
      /// The field is optional (can be null) and each record has 0 or 1 values.
      /// </summary>
      OPTIONAL = 1,
      /// <summary>
      /// The field is repeated and can contain 0 or more values
      /// </summary>
      REPEATED = 2,
   }
}
