/*
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Parquet.Thrift
{
   /// <summary>
   /// Types supported by Parquet.  These types are intended to be used in combination
   /// with the encodings to control the on disk storage format.
   /// For example INT16 is not included as a type since a good encoding of INT32
   /// would handle this.
   /// </summary>
   enum Type
   {
      BOOLEAN = 0,
      INT32 = 1,
      INT64 = 2,
      INT96 = 3,
      FLOAT = 4,
      DOUBLE = 5,
      BYTE_ARRAY = 6,
      FIXED_LEN_BYTE_ARRAY = 7,
   }
}
